### ISSUE TITLE
Needs reference to ServiceStack.Interfaces 3.9.9.0

### ISSUE THREAD

**Issue by jeffijoe** [TheCloudlessSky/NHibernate.Caches.Redis#12] opened 2015-04-16 18:30 UTC
Hi!

Trying to set up NH Redis Cache, but I get these errors when compiling:

```
The type 'ServiceStack.Redis.IRedisNativeClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'ServiceStack.Interfaces, Version=3.9.9.0, Culture=neutral, PublicKeyToken=null'.
The type 'ServiceStack.Redis.IRedisClientsManager' is defined in an assembly that is not referenced. You must add a reference to assembly 'ServiceStack.Interfaces, Version=3.9.9.0, Culture=neutral, PublicKeyToken=null'.
The type 'ServiceStack.Redis.IRedisClientCacheManager' is defined in an assembly that is not referenced. You must add a reference to assembly 'ServiceStack.Interfaces, Version=3.9.9.0, Culture=neutral, PublicKeyToken=null'.
The type 'ServiceStack.Redis.IRedisClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'ServiceStack.Interfaces, Version=3.9.9.0, Culture=neutral, PublicKeyToken=null'.
```

Problem is, the ServiceStack included here is v4.

This is with a fresh installation of NHibernate.Caches.Redis.

Weird thing is, in the editor everything looks good.

**Comment by TheCloudlessSky** [comment] 2015-04-16 18:49
I'm guessing it's ServiceStack's packages because I've had [similar issues with another project](https://github.com/TheCloudlessSky/Harbour.RedisSessionStateStore/issues/15). That being said, the main master branch isn't really supported right now because I'm going to be publishing V2 with drops support for ServiceStack.Redis all together (and switching to StackExchange.Redis).

Can you use [the `stackexchange-redis` branch](https://github.com/TheCloudlessSky/NHibernate.Caches.Redis/tree/stackexchange-redis) instead?

**Comment by jeffijoe** [comment] 2015-04-16 18:56
I'll try this on sunday - not guessing there's a Nuget package for it?

**Comment by jeffijoe** [comment] 2015-04-16 18:59
- by the way, love your Github avatar! LoZ is for winners!

**Comment by TheCloudlessSky** [comment] 2015-04-16 19:08
Yup, [there's a Nuget package for it](https://www.nuget.org/packages/NHibernate.Caches.Redis/2.0.0-alpha9). But I'll be publishing the full 2.0 release here shortly...

And yes, :+1: for LoZ!

**Comment by TheCloudlessSky** [comment] 2015-04-16 19:21
Ok, I've just pushed the final 2.0 release and merged in the `stackexchange-redis` branch, so you can now build from `master`.

**Comment by jeffijoe** [comment] 2015-04-16 19:29
Sweet - can't try it yet though, but will on sunday.

**Comment by TheCloudlessSky** [comment] 2015-04-16 19:32
:+1:

**Comment by jeffijoe** [comment] 2015-04-19 15:33
Yep, that fixed it. However when I close my redis server and attempt to do something with NH, it breaks. Is this expected behavior? I don't want my redis downtime to cause my entire app to cry. :P

**Comment by TheCloudlessSky** [comment] 2015-04-19 19:22
Yup, that's expected behavior. However, if you need to allow NHibernate to continue without cache access (in case it fails), you can [do something similar to what's in the README](https://github.com/TheCloudlessSky/NHibernate.Caches.Redis#exception-handling) :smile: .

**Closed by TheCloudlessSky** 2015-04-19 19:22 UTC

**Comment by jeffijoe** [comment] 2015-04-19 20:56
> You may require that we gracefully continue to the database as if we "missed" the cache if an exception occurs. **By default, this is what happens**.

But, it doesen't? :)

**Comment by TheCloudlessSky** [comment] 2015-04-19 23:21
Ah, right that was from the previous 1.x version. I've updated it to reflect that 2.0 doesn't do anything.

**Comment by thebiggestlebowski** [comment] 2015-05-05 16:29
I've got a similar (but not the same) problem.  A number of the assembly references match.  On my local box build works fine.  When I try to do on CI server, compilation complains because it doesn't find these dependencies.  Suggestion?  Am I in the right place?  If not, where should I go (know I'm close)?

ServiceStack.Caching.ICacheClient
ServiceStack.Caching.ICacheClientExtended
ServiceStack.Caching.IRemoveByPattern
ServiceStack.Data.IEntityStore
ServiceStack.Redis.IRedisClient
ServiceStack.Redis.IRedisNativeClient

**Comment by TheCloudlessSky** [comment] 2015-05-05 16:34
@thebiggestlebowski It really seems like ServiceStack messed up some bounds on their Nuget packages because I've had similar problems with other projects. Your best bet is to upgrade to 2.0 which uses StackExchange.Redis instead of ServiceStack.Redis (and doesn't have a dependency mess).
